name = "Mermaid"
uuid = "922b6a97-db6b-4881-a67b-b45fb8a31c4c"
authors = ["Matt J. Owen <matt.owen@bristol.ac.uk>"]
version = "0.1.0"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[weakdeps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
MethodOfLines = "94925ecb-adb7-4558-8ed8-f975c56a0bf4"
Surrogates = "6fc51010-71bc-11e9-0e15-a3fcc6593c49"
TrixiParticles = "66699cd8-9c01-4e9d-a059-b96c86d16b3a"

[extensions]
DiffEqExt = "DiffEqBase"
MethodOfLinesExt = ["MethodOfLines", "DiffEqBase"]
SurrogatesExt = "Surrogates"
TrixiParticlesExt = "TrixiParticles"

[compat]
CommonSolve = "0.2.4"
DiffEqBase = "6.190.2"
DocStringExtensions = "0.9.5"
Flux = "0.16.5"
MethodOfLines = "0.11.9"
OrderedCollections = "1.8.1"
Surrogates = "7.0.1"
TrixiParticles = "0.4.3"
julia = "1.10"

[workspace]
projects = ["test", "docs"]
