[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CellMLToolkit = "03cb29e0-1ef4-4721-aa24-cf58a006576f"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DocInventories = "43dc2714-ed3b-44b5-b226-857eda1aa7de"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Mermaid = "922b6a97-db6b-4881-a67b-b45fb8a31c4c"
MethodOfLines = "94925ecb-adb7-4558-8ed8-f975c56a0bf4"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Surrogates = "6fc51010-71bc-11e9-0e15-a3fcc6593c49"

[compat]
BenchmarkTools = "1.6.3"
CairoMakie = "0.13.10"
CellMLToolkit = "2.15.0"
CommonSolve = "0.2.6"
DocInventories = "1"
DocStringExtensions = "0.9.5"
Documenter = "1.11"
DocumenterInterLinks = "1.1.0"
DocumenterTools = "0.1.21"
Makie = "0.22.10"
OrderedCollections = "1.8.1"
OrdinaryDiffEq = "6.108.0"
Plots = "1.41.5"
Random = "1.11"
Surrogates = "7.4.0"
